[package]
name = "walk_base_2_data_db"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
derive-getters = "0.2.0"
derive-new = "0.5.9"
mockall = "0.10.2"
once_cell = "1.8.0"
paste = "1.0.5"
pretty_assertions = "0.7.2"
num-traits = "0.2.14"
rusqlite = {version = "0.25.3", features = ["bundled"]}
test-case = "1.2.0"
thiserror = "1.0.26"

domain = { path = "../domain", package = "walk_base_2_domain" }
media = { path = "../media", package = "walk_base_2_media" }
