[package]
name = "walk_base_2_domain"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
derive-new = "0.7.0"
mockall = "0.13.1"
num-derive = "0.4.2"
num-traits = "0.2.19"
once_cell = "1.21.3"
paste = "1.0.15"
rusqlite = {version = "0.37.0", features = ["bundled"]}
test-case = "3.3.1"
thiserror = "2.0.12"

media = { path = "../media", package = "walk_base_2_media" }
