[package]
name = "walk_base_2_app"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.88"
mockall = "0.13.1"
paste = "1.0.5"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-rustls"] }
test-case = "3.3.1"
thiserror = "2.0.12"
toml = "0.9.0"

domain = { path = "../domain", package = "walk_base_2_domain" }
media = { path = "../media", package = "walk_base_2_media" }
