[package]
name = "walk_base_2_app"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
mockall = "0.10.2"
paste = "1.0.5"
test-case = "1.2.0"
thiserror = "1.0.26"
toml = "0.5.8"

domain = { path = "../domain", package = "walk_base_2_domain" }
media = { path = "../media", package = "walk_base_2_media" }
